[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "curios-fits-imaging"
version = "2.9.0"
description = "Python tools for analyzing CuRIOS FITS images"
readme = "README.md"
requires-python = ">=3.12"

authors = [
    { name = "Steven Beckwith" }
]

license = { text = "MIT" }

keywords = [
    "astronomy",
    "FITS",
    "astrophotography",
    "photometry",
    "image-processing"
]

dependencies = [
    "numpy>=2,<3",
    "scipy>=1.13",
    "matplotlib>=3.8.4",
    "astropy @ git+https://github.com/rithwiksud/astropy.git@5ef78cde85fdaf07e7edb68b80062e1add366dd8",
    "imagecodecs>=2026.1.1",
    "pandas>=2.2.2"
]

[project.optional-dependencies]
gui = [
    "PySide6",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["fits_imaging*"]
    
[project.scripts]
curios-fits = "fits_imaging.cli:main"
curios-fits-gui = "fits_imaging.gui:main"
