""""Central plotting style constants for fits_imaging."""

# Main image plot
MAIN_TITLE_SIZE = 18
MAIN_LABEL_SIZE = 14
MAIN_TICK_SIZE = 12

MAIN_GRID_COLOR = "0.94"
MAIN_GRID_ALPHA = 0.45
MAIN_GRID_WIDTH = 0.35

MAIN_CENTER_COLOR = "red"
MAIN_CENTER_SIZE = 18

MAIN_PEAK_LABEL_COLOR = "red"
MAIN_PEAK_LABEL_SIZE = 9

CIRCLE_MARK_COLOR = "red"
CIRCLE_MARK_SIZE = 14

# Peak cutouts
CUTOUT_TITLE_SIZE = 12
CUTOUT_LABEL_SIZE = 10
CUTOUT_TICK_SIZE = 10

CUTOUT_CENTER_COLOR = "red"
CUTOUT_CENTER_SIZE = 10
CUTOUT_CENTER_WIDTH = 1.5

# Histograms
HIST_TITLE_SIZE = 14
HIST_LABEL_SIZE = 12
HIST_TICK_SIZE = 10

HIST_GRID_COLOR = "0.90"
HIST_GRID_ALPHA = 0.6
HIST_GRID_WIDTH = 0.7
